apiVersion: v1
kind: Service
metadata:
  name: bank-server
  namespace: bank-server
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      name: http
  selector:
    app: bank-server
