apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wonq-order-server
  namespace: argocd
spec:
  destination:
    namespace: wonq-order-server
    server: https://kubernetes.default.svc
  source:
    path: manifests/wonq-order/server
    repoURL: https://github.com/WON-Q/infra
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
