apiVersion: v1
kind: Service
metadata:
  name: pg-client
  namespace: pg-client
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: pg-client
