apiVersion: v1
kind: Service
metadata:
  name: pg-client
  namespace: pg-client
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3000
      name: https
  selector:
    app: pg-client
