apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-server
  namespace: pg-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-server
  template:
    metadata:
      labels:
        app: pg-server
    spec:
      containers:
        - name: pg-server
          image: asia-northeast3-docker.pkg.dev/fisa-wonq-order/pg/server:latest
          ports:
            - containerPort: 8080
