apiVersion: v1
kind: Service
metadata:
  name: pg-server
  namespace: pg-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: pg-server
