apiVersion: v1
kind: Service
metadata:
  name: pg-server
  namespace: pg-server
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      name: https
  selector:
    app: pg-server
