apiVersion: apps/v1
kind: Deployment
metadata:
  name: card-server
  namespace: card-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: card-server
  template:
    metadata:
      labels:
        app: card-server
    spec:
      containers:
        - name: card-server
          image: asia-northeast3-docker.pkg.dev/fisa-wonq-order/card/server:latest
          ports:
            - containerPort: 8080
