apiVersion: v1
kind: Service
metadata:
  name: card-server
  namespace: card-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: card-server
