apiVersion: v1
kind: Service
metadata:
  name: wonq-order-server
  namespace: wonq-order-server
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 8080
      name: https
  selector:
    app: wonq-order-server
