apiVersion: v1
kind: Service
metadata:
  name: wonq-order-server
  namespace: wonq-order-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: wonq-order-server
