apiVersion: v1
kind: Service
metadata:
  name: app-card-server
  namespace: app-card-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: app-card-server
