apiVersion: apps/v1
kind: Deployment
metadata:
  name: wonq-order-merchant-client
  namespace: wonq-order-merchant-client
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wonq-order-merchant-client
  template:
    metadata:
      labels:
        app: wonq-order-merchant-client
    spec:
      containers:
        - name: wonq-order-merchant-client
          image: asia-northeast3-docker.pkg.dev/fisa-wonq-order/wonq-order/merchant-client:0.1.0
          ports:
            - containerPort: 3000
