apiVersion: v1
kind: Service
metadata:
  name: wonq-order-user-client
  namespace: wonq-order-user-client
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: wonq-order-user-client
